### ISSUE TITLE
`accessible=true` prop on Fluent Tester root view breaks element querying on iOS E2E tests

### ISSUE THREAD

**Issue by lawrencewin** [microsoft/fluentui-react-native#2264] opened 2022-10-21 17:45 UTC
### Willing to submit a PR to fix?

- [ ] I am willing to submit a PR to fix

### Requested priority

Normal

### Products/applications affected

CI fails without disabling the accessible prop on ios for this PR: https://github.com/microsoft/fluentui-react-native/pull/2226 

### Package version(s)
```
- yarn 1.22.19
- npm 8.0.0
- react-native ^0.68.0
- react-native-macos ^0.68.0
- appium 2.0.0-beta.41
- appium-xcuitest-driver 4.11.1
```

### OS version(s)

iOS 15.5

### Platform

- [X] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [ ] android

### Xcode version

xCode 14.0.1

### Please provide a reproduction of the bug

1. Clone this PR: https://github.com/microsoft/fluentui-react-native/pull/2226
2. In `apps/fluent-tester/src/FluentTester.tsx`, change the `accessible` prop on the `View` with `testID={ROOT_VIEW}` from `Platform.OS === 'ios'` to `true`.
```tsx
  return (
    // TODO: Figure out why making this view accessible breaks element querying on iOS.
    <View accessible={Platform.OS !== 'ios'} testID={ROOT_VIEW} style={commonTestStyles.flex}>
      {Platform.OS === ('win32' as any) ? (
        <FocusTrapZone style={themedStyles.root}>
          <TesterContent />
        </FocusTrapZone>
      ) : (
        <RootView style={themedStyles.root}>
          <TesterContent />
        </RootView>
      )}
    </View>
  );

```
3. From `apps/fluent-tester`, run `yarn ios` to build the iOS app. Then, once the app is running, run `yarn e2etest:ios` to run the E2E test suite. Watch the tests fail. (if you don't have a mac, just run this in the CI)

### Actual behavior

The compiled native app returns this view hierarchy:
![ca73c893-602a-4fe6-9094-b335db00b42d](https://user-images.githubusercontent.com/15683103/197255516-e28b9624-0161-4d3f-a889-8ea4c1ff58c7.jpg)

When querying elements in appium with strategy `accessibility id`, we start from the highlighted RCTView with accessibility id `Fluent_Tester_Root_View`. For each chained query, we try and find the RCTTextView saying "Fluent UI Tests", which is a direct child of `Fluent_Tester_Root_View`. This query always fails when the view is accessible.

### Expected behavior

Given that the RCTTextView is a direct child of our starting View, our query should succeed and return the text view.

**Comment by lyzhan7** [comment] 2022-12-09 01:38
@lawrencewin @Saadnajmi 

Did some investigation into this and I actually think the right thing to do is keep accessibility set to false for iOS. I was wondering why we wanted to set accessible to be true in the first place? Is there a bug if it's not set to true on other platforms? Do we get some specific benefit on other platforms?

From [react native documentation](https://reactnative.dev/docs/accessibility#accessible) about the accessible prop:
> When true, indicates that the view is an accessibility element. When a view is an accessibility element, it groups its children into a single selectable component. By default, all touchable elements are accessible.

So when the root view has the accessible prop set to true, the whole view becomes a single accessibility element. I've confirmed that when I try running the e2e tests with accessible=true set, it can find the root view, but can't find anything else. 

Also used the Xcode accessibility inspector tool to confirm this:

| accessible = true on root view | accessible = false on root view |
| - | - |
| <img width="838" alt="Screenshot 2022-12-08 at 4 59 29 PM" src="https://user-images.githubusercontent.com/78454019/206601418-c3b1a633-4ec2-4f08-9c5e-176e8026be11.png"> | <img width="847" alt="Screenshot 2022-12-08 at 4 57 07 PM" src="https://user-images.githubusercontent.com/78454019/206601721-58595750-aa82-4ab7-8b03-100f2dea621a.png"> |

The inspector can't find any individual items on the page. The accessibility label on the root view also gets changed and combined all of its children's accessibility labels, something like _"Base_TestPage ‹ Back Theme Brand Homepage_ActivityIndicator_Button Homepage_Avatar_Button Homepage_Native_Avatar_Button Homepage_Badge_Button Homepage_Button_Button Homepage_Checkbox_Button ...."_ 

Also I think the react native accessible prop gets translated on iOS to the isAccessibilityElement property - and from [documentation about isAccessibilityElement](https://developer.apple.com/documentation/objectivec/nsobject/1615141-isaccessibilityelement):
> The default value for this property is false unless the element is a standard UIKit control, in which case, the value is true.
> 
> Assistive apps can get information only about objects that accessibility elements represent. Therefore, if you implement a custom control or view that you want to be accessible to users with disabilities, set this property to true. **The only exception to this practice is a view that merely serves as a container for other items that you want to be accessible**

Seems like setting the root view would be an exception since it's a container for the test page buttons that we do want to be accessible.

**Comment by Saadnajmi** [comment] 2022-12-09 03:17
@harrieshin was there something new in iOS 15 or 16 where you could have nested accessibility elements?

**Comment by harrieshin** [comment] 2022-12-09 03:49
no there is no nested accessibility elements in iOS. it makes no sense for the touch screen user. iOS does have better support of grouping alot of accessibilityelement into one via .combine

**Comment by lyzhan7** [comment] 2022-12-15 17:33
Update - seems like setting accessible=true is the right thing to do on windows, and I also tested the macOS FluentTester with the accessibility inspector, and confirmed that it doesn't have the same issue as iOS. Confirmed that iOS is the exception here and we should keep accessible=false for iOS only. Updated the comment in FluentTester to explain this, and closing this issue

**Closed by lyzhan7** 2022-12-15 17:33 UTC
Labels: Needs: Triage :mag:
