### ISSUE TITLE
Missing SVG in package causing tests to fail

### ISSUE THREAD

**Issue by rychomis** [microsoft/fluentui-react-native#989] opened 2021-09-07 23:37 UTC
### Environment Information

- **Package version(s)**:
    "@fluentui-react-native/apple-theme": "^0.7.20",
    "@fluentui-react-native/default-theme": "^0.8.0",
    "@fluentui-react-native/theme": "^0.5.18",
    "@fluentui-react-native/theme-types": "^0.11.1",
    "@fluentui-react-native/win32-theme": "^0.12.0",
    "@fluentui/react-native": "0.25.10",

- **Platform**:
  - [ x] win32
  - [ x] windows
  - [ x] android

### Please provide a reproduction of the bug:

cannot run tests due to chevron.svg (referenced by @fluentui-react-native/menu-button/lib-commonjs/MenuButton.js) being missing from the imported node package

full error
```
    Cannot find module './chevron.svg' from '../../common/temp/node_modules/.pnpm/@fluentui-react-native/menu-button@0.6.3_d5e23968334f53e1be2a7f54b545444e/node_modules/@fluentui-react-native/menu-button/lib-commonjs/MenuButton.js'
    Require stack:
      D:/fabric-internal/common/temp/node_modules/.pnpm/@fluentui-react-native/menu-button@0.6.3_d5e23968334f53e1be2a7f54b545444e/node_modules/@fluentui-react-native/menu-button/lib-commonjs/MenuButton.js
      D:/fabric-internal/common/temp/node_modules/.pnpm/@fluentui-react-native/menu-button@0.6.3_d5e23968334f53e1be2a7f54b545444e/node_modules/@fluentui-react-native/menu-button/lib-commonjs/index.js
      D:/fabric-internal/common/temp/node_modules/.pnpm/@fluentui/react-native@0.25.10_eb4a285c50e8afb4cac1b17808e43875/node_modules/@fluentui/react-native/lib-commonjs/index.js
      src/RefreshOptions.native.tsx
      __tests__/leafComponents.test.win32.tsx

      at Resolver.resolveModule (../../common/temp/node_modules/.pnpm/jest-resolve@26.6.2/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../../common/temp/node_modules/.pnpm/@fluentui-react-native/menu-button@0.6.3_d5e23968334f53e1be2a7f54b545444e/node_modules/@fluentui-react-native/menu-button/src/MenuButton.tsx:9:1)
```

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/applications affected:
Excel task pane

**Comment by Saadnajmi** [comment] 2021-09-08 02:42
Duplicate of #958 I think. 
@ValentinaKozlova FYI

**Comment by Saadnajmi** [comment] 2021-09-10 03:32
Duplicate of #958

**Closed by Saadnajmi** 2021-09-10 03:32 UTC
